apiVersion: v1
kind: Service
metadata:
  name: votesystem
  labels:
    run: votesystem
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: votesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: votesystem
spec:
  selector:
    matchLabels:
      run: votesystem
  replicas: 1
  template:
    metadata:
      labels:
        run: votesystem
    spec:
      containers:
      - name: votesystem-container
        image: $IMAGENAME$
        ports:
        - containerPort: 443
        - containerPort: 80
