apiVersion: v1
kind: Service
metadata:
  name: votesystem-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: votesystem
  ports:
    - protocol: TCP
      port: 80
      targetPort: 30000