
name: CICD Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ECR_REPOSITORY: votesystem
  REGION: us-east-1
  IMAGE_TAG: votesystem:${{ github.sha }}
  ECR_URI: ${{ secrets.ECR_URI }}

jobs:
  build-and-push:

    runs-on: ubuntu-latest
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}

    steps:

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}
   
        

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        cd vote_system
        docker build -t $ECR_REGISTRY/$IMAGE_TAG .
        docker push $ECR_REGISTRY/$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$IMAGE_TAG"}

  deploy-to-cluster:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # inject image name into yaml
    - name: replace image name in k8s yaml
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: $IMAGENAME$
        replace: ${{ env.IMAGE_TAG }}

    - name: add deployment to cluster
      uses: Jberlinsky/kubernetes-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f /github/workspace/vote_system/kubernetes_deployment.yaml
        include: "kubernetes_deployment.yaml"

    - name: verify deployment
      uses: Jberlinsky/kubernetes-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: rollout status deployment/${{ env.ECR_REPOSITORY }}